version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
          - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
    
  dataplayground:
    
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - ./data_model.ipynb:/home/joyyan/data_model.ipynb
    ports:
      - "8888:8888"